name = "BenchmarkConfigSweeps"
uuid = "5dead3b6-c9e4-435a-a292-80e2716ed6d9"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Accessors = "0.1"
ArgCheck = "2"
AutoHashEquals = "0.2"
BenchmarkTools = "1"
JSON3 = "1"
StructTypes = "1"
Tables = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestFunctionRunner = "792026f5-ac9a-4a19-adcb-47b0ce2deb5d"

[targets]
test = ["Aqua", "Test", "TestFunctionRunner"]
